# Test GitLab (GL) scripts

include:
  - local: 'test/gl/setup-dkml.gitlab-ci.yml'

# Test personal computer (PC) scripts

test-pc-windows:
  stage: build # no point waiting for the build phase of `local: 'test/gl/setup-dkml.gitlab-ci.yml'`
  parallel:
    matrix:
      - dkml_host_abi: windows_x86
      - dkml_host_abi: windows_x86_64

  tags:
    - shared-windows
    - windows
    - windows-1809

  script:
    - '& test\pc\setup-dkml-${env:dkml_host_abi}.ps1'

test-pc-linux:
  stage: build # no point waiting for the build phase of `local: 'test/gl/setup-dkml.gitlab-ci.yml'`
  parallel:
    matrix:
      - dkml_host_abi: linux_x86
      - dkml_host_abi: linux_x86_64

  script:
    - sh test/pc/setup-dkml-${dkml_host_abi}.sh
